import { useEffect, useState } from 'react'
import { FlaskConical, RefreshCw, Settings2, Wrench, X } from 'lucide-react'
import { useAppStore } from '../../store/appStore'
import { cn } from '../../lib/cn'
import { toast } from 'sonner'
import type { PaymentResult } from '../../types'

export function DemoControls() {
  const [open, setOpen] = useState(false)
  const reset = useAppStore((s) => s.resetDemo)
  const next = useAppStore((s) => s.nextPaymentResult)
  const setNext = useAppStore((s) => s.setNextPaymentResult)
  const addTx = useAppStore((s) => s.fundWallet)
  const users = useAppStore((s) => s.users)
  const role = useAppStore((s) => s.role)
  const activeId = useAppStore((s) => s.activeUserId)
  const adminAction = useAppStore((s) => s.adminAction)
  const updateKyc = useAppStore((s) => s.updateKyc)
  const kycDraft = useAppStore((s) => s.kycDraft)
  const push = useAppStore((s) => s.pushNotification)

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.ctrlKey && e.shiftKey && e.key.toLowerCase() === 'd') {
        e.preventDefault()
        setOpen((o) => !o)
      }
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [])

  const demoUser = users.find((u) => u.id === activeId)

  const actions: { label: string; desc: string; run: () => void; danger?: boolean }[] = [
    {
      label: 'Reset demo data',
      desc: 'Restore all balances, transactions & session',
      run: () => {
        reset()
        setOpen(false)
        toast.success('Demo data reset', { description: 'All prototype state restored to defaults.' })
      },
      danger: true,
    },
    {
      label: 'Add sample credit (+₦10,000)',
      desc: 'Inserts a successful wallet funding',
      run: () => {
        addTx(10000, 0, 'Card · demo control', 'card')
        toast.success('Sample transaction added')
      },
    },
    {
      label: 'Simulate notification',
      desc: 'Push a random demo alert',
      run: () => {
        push({
          category: 'system',
          title: 'Demo notification',
          body: `This alert was generated by the Demo Control Panel at ${new Date().toLocaleTimeString()}.`,
          audience: role === 'admin' ? 'admin' : 'user',
        })
        toast.success('Notification sent')
      },
    },
    {
      label: 'Set low balance (₦500)',
      desc: 'Make the wallet balance low',
      run: () => {
        const store = useAppStore.getState()
        useAppStore.setState({
          wallets: store.wallets.map((w) => (w.userId === activeId ? { ...w, availableBalance: 500, ledgerBalance: 500 } : w)),
        })
        toast.success('Balance set to ₦500')
      },
    },
    {
      label: demoUser && demoUser.status === 'active' ? 'Restrict current user' : 'Activate current user',
      desc: demoUser?.status === 'active' ? 'Toggle a restricted account state' : 'Restore the current user to active',
      run: () => {
        if (!activeId) return toast.error('Sign in as a customer first')
        const st = demoUser?.status
        adminAction(st === 'active' ? 'restrict' : 'activate', activeId)
        toast.success(st === 'active' ? 'Account restricted' : 'Account activated')
      },
    },
  ]

  return (
    <>
      <button
        onClick={() => setOpen(true)}
        className="fixed bottom-4 left-4 z-40 hidden h-10 items-center gap-2 rounded-full border border-brand/25 bg-white/90 px-3.5 text-xs font-semibold text-brand shadow-card backdrop-blur transition-colors hover:bg-brand hover:text-white no-print md:inline-flex"
        title="Demo Control Panel (Ctrl+Shift+D)"
      >
        <FlaskConical className="h-4 w-4" /> Demo
      </button>
      {open && (
        <div className="fixed inset-0 z-[60] flex items-end justify-center p-0 sm:items-center sm:p-4 no-print">
          <div className="absolute inset-0 bg-ink/40 backdrop-blur-[1px]" onClick={() => setOpen(false)} />
          <div className="relative w-full max-w-md overflow-hidden rounded-t-3xl bg-white shadow-pop sm:rounded-2xl animate-scale-in">
            <div className="flex items-center gap-3 border-b border-line bg-gradient-to-r from-brand to-brand-deep px-5 py-4 text-white">
              <span className="flex h-9 w-9 items-center justify-center rounded-lg bg-white/15"><Settings2 className="h-5 w-5" /></span>
              <div>
                <h3 className="text-sm font-bold">Demo Control Panel</h3>
                <p className="text-[11px] text-white/70">Development only — for predictable stakeholder presentations</p>
              </div>
              <button onClick={() => setOpen(false)} className="ml-auto rounded-lg p-1.5 text-white/70 hover:bg-white/10" aria-label="Close">
                <X className="h-5 w-5" />
              </button>
            </div>
            <div className="max-h-[60vh] space-y-3 overflow-y-auto p-5">
              {/* Payment outcome */}
              <div>
                <p className="mb-2 flex items-center gap-1.5 text-[13px] font-semibold text-ink"><Wrench className="h-4 w-4 text-brand" /> Next payment outcome</p>
                <div className="flex gap-2">
                  {(['success', 'pending', 'failed'] as PaymentResult[]).map((r) => (
                    <button
                      key={r}
                      onClick={() => {
                        setNext(r)
                        toast.success(`Next payment will ${r}`)
                      }}
                      className={cn(
                        'flex-1 rounded-xl border px-3 py-2 text-sm font-semibold capitalize transition-all',
                        next === r
                          ? r === 'success'
                            ? 'border-brand bg-brand text-white'
                            : r === 'pending'
                              ? 'border-amber-500 bg-amber-500 text-white'
                              : 'border-status-danger bg-status-danger text-white'
                          : 'border-line text-ink-soft hover:border-brand/40',
                      )}
                    >
                      {r}
                    </button>
                  ))}
                </div>
              </div>

              {/* KYC outcome */}
              <div>
                <p className="mb-2 text-[13px] font-semibold text-ink">KYC outcome</p>
                <div className="flex gap-2">
                  {(['verified', 'in_review', 'rejected'] as const).map((s) => (
                    <button
                      key={s}
                      onClick={() => {
                        updateKyc({ status: s })
                        toast.success(`KYC set to ${s}`)
                      }}
                      className={cn(
                        'flex-1 rounded-xl border px-3 py-2 text-sm font-medium capitalize transition-all',
                        kycDraft.status === s ? 'border-brand bg-brand-soft text-brand' : 'border-line text-ink-soft hover:border-brand/40',
                      )}
                    >
                      {s.replace('_', ' ')}
                    </button>
                  ))}
                </div>
              </div>

              {actions.map((a) => (
                <button
                  key={a.label}
                  onClick={a.run}
                  className={cn('w-full rounded-xl border px-4 py-2.5 text-left transition-colors', a.danger ? 'border-red-200 bg-red-50/50 hover:bg-red-50' : 'border-line hover:bg-canvas')}
                >
                  <span className={cn('block text-sm font-semibold', a.danger ? 'text-red-700' : 'text-ink')}>
                    {a.label}
                  </span>
                  <span className="block text-xs text-ink-soft">{a.desc}</span>
                </button>
              ))}
              <p className="flex items-center gap-1.5 text-[11px] text-ink-faint">
                <RefreshCw className="h-3 w-3" /> Shortcut: <kbd className="rounded bg-canvas px-1.5 py-0.5 font-mono">Ctrl</kbd> + <kbd className="rounded bg-canvas px-1.5 py-0.5 font-mono">Shift</kbd> + <kbd className="rounded bg-canvas px-1.5 py-0.5 font-mono">D</kbd>
              </p>
            </div>
          </div>
        </div>
      )}
    </>
  )
}
